channels:
  - defaults
dependencies:
  - conda-package-handling >=1.3.0
  - pycosat >=0.6.3
  - pyopenssl >=16.2.0
  - requests >=2.18.4,<3
  - ruamel_yaml >=0.11.14,<0.17
  - setuptools >=31.0.1
  - toolz >=0.8.1
  - cython
  - zstandard
  - pip:
    - conda-package-streaming
    - requests-cache
    - jsonpatch
